site_name: ERP Reimagined Knowledge
theme:
  name: material

plugins:
  - search
  - tags        # enables tag chips + /tags/ index

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences   # required for advanced fences + tabs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details       # collapsible "details" blocks

nav:
  - index.md
  - Workspaces:
      - Overview: workspaces/index.md
      - Live System: workspaces/live-system.md
      - Reporting Copy: workspaces/live-system-rpts-copy.md
      - Data Import:
          - Overview: workspaces/data-import/index.md
          - CSV Import: workspaces/data-import/csv-import.md

  - Knowledge & Help:
      - Overview: knowledge/index.md
      - Reports:
          - Overview: knowledge/reports/index.md
          - Standard Reports: knowledge/reports/standard-reports.md
          - Prior Period Reports: knowledge/reports/prior-period-reports.md
          - Custom Reports: knowledge/reports/custom-reports.md
      - Data Import:
          - Overview: knowledge/data-import/index.md
          - CSV Import: knowledge/data-import/csv-import.md
      - Storage Locations: knowledge/storage-locations.md
      - GnuCash:
          - Settings & Preferences: knowledge/gnucash-settings.md
          - Backup & Restore: knowledge/backup-restore.md
      - Examples & Patterns:
          - How we write pages: examples/patterns.md
      - Tags: tags.md      # generated by the 'tags' plugin
  - Feedback & Issues:
      - Overview: feedback-issues/index.md
      - Problem Reports:
          - Overview: feedback-issues/problems/index.md
          - Bank Reconciliation Button Missing: feedback-issues/problems/bank-recon-button-missing.md
      - Suggestions:
          - Overview: feedback-issues/suggestions/index.md
          - Add Aging Shortcut: feedback-issues/suggestions/add-aging-shortcut.md
      - Corrections:
          - Overview: feedback-issues/corrections/index.md
          - Typo in Invoice Template: feedback-issues/corrections/typo-in-invoice-template.md

  - Community & Fun:
      - Overview: community-fun/index.md
      - Jokes:
          - Insomnia: community-fun/jokes/insomnia.md
          - Balloon: community-fun/jokes/balloon.md
          - 2 + 2: community-fun/jokes/2plus2.md
      - Tips & Tricks:
          - Overview: community-fun/tips-and-tricks/index.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
